name: Smart Translation Workflow

concurrency:
  group: translate-${{ github.event.client_payload.documentId || inputs.documentId || inputs.document_id || github.run_id }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [sanity_article_ja]
  workflow_dispatch:
    inputs:
      documentId:
        description: 'Sanity document ID to translate'
        required: true
        type: string
      force:
        description: 'Force re-translation even if translations exist'
        required: false
        type: boolean
        default: false
      dryRun:
        description: 'Dry run mode'
        required: false
        type: boolean
        default: false

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter shared build
          pnpm --filter worker build

      - name: Extract document info
        id: extract-info
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            DOCUMENT_ID="${{ github.event.client_payload.documentId }}"
            TITLE="${{ github.event.client_payload.title }}"
            TRIGGERED_BY="${{ github.event.client_payload.triggeredBy }}"
            HAS_IMAGES="${{ github.event.client_payload.hasImages }}"
          else
            DOCUMENT_ID="${{ inputs.documentId }}"
            TITLE="Manual trigger"
            TRIGGERED_BY="workflow_dispatch"
            HAS_IMAGES="true"
          fi
          
          echo "document-id=$DOCUMENT_ID" >> $GITHUB_OUTPUT
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "triggered-by=$TRIGGERED_BY" >> $GITHUB_OUTPUT
          echo "has-images=$HAS_IMAGES" >> $GITHUB_OUTPUT

      - name: Run translation
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_API_VERSION: ${{ secrets.SANITY_API_VERSION }}
        run: |
          if [ "${{ inputs.dryRun }}" = "true" ]; then
            echo "🔍 Dry run mode - checking translation conditions"
            pnpm --filter worker run start "${{ steps.extract-info.outputs.document-id }}" --languages pt-br --dry-run
          else
            echo "🚀 Starting translation for document: ${{ steps.extract-info.outputs.document-id }}"
            FORCE_ARG=""
            if [ "${{ inputs.force }}" = "true" ]; then
              FORCE_ARG="--force"
            fi
            pnpm --filter worker run start "${{ steps.extract-info.outputs.document-id }}" --languages pt-br $FORCE_ARG
          fi

      - name: Commit translated files
        if: ${{ inputs.dryRun != true }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add any new translation files
          git add -A

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No translation files to commit"
          else
            git commit \
              -m "chore: add translations for ${{ steps.extract-info.outputs.title }}" \
              -m "Triggered by: ${{ steps.extract-info.outputs.triggered-by }}" \
              -m "Document ID: ${{ steps.extract-info.outputs.document-id }}" \
              -m "Has images: ${{ steps.extract-info.outputs.has-images }}" \
              -m "Co-Authored-By: Claude <noreply@anthropic.com>"

            git push
            echo "✅ Translations committed and pushed"
          fi

      - name: Summary
        run: |
          echo "## Translation Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Document ID**: ${{ steps.extract-info.outputs.document-id }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Title**: ${{ steps.extract-info.outputs.title }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ steps.extract-info.outputs.triggered-by }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Has images**: ${{ steps.extract-info.outputs.has-images }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Dry run**: ${{ inputs.dryRun }}" >> $GITHUB_STEP_SUMMARY